version: '3.8'
services:
  api:
    build:
      context: .
      target: runtime
    command: uvicorn rei.app:app --port 8000 --host 0.0.0.0 --proxy-headers --no-use-colors
    ports:
      - ${PORT}:8000
    restart: unless-stopped
    env_file:
      - .env
