name: Build and push to registry

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout to current branch
      uses: actions/checkout@v4

    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v1

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        context: .
        target: runtime
        push: true
        tags: |
          ghcr.io/unicheckbot/rei:latest
          ghcr.io/unicheckbot/rei:${{ github.event.release.tag_name }}
