name: Build and push to registry

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout to current branch
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        target: runtime
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/unicheckbot/rei:latest
          ghcr.io/unicheckbot/rei:${{ github.event.release.tag_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
